"""
run_zenodo_lgbm_only.py — LightGBM VLE-only baseline on Zenodo data.

Runs WITHOUT importing PyTorch so it fits in memory after the graph-build
subprocess has freed its pages.  Reads pre-built artifacts from
results/zenodo/artifacts/week08_*.parquet (generated by run_zenodo_pipeline.py
stages A–C) and outputs results/zenodo/comparison_results.csv.

Usage
-----
    python src/run_zenodo_lgbm_only.py
    python src/run_zenodo_lgbm_only.py --seeds 42 123 7 17 99
    python src/run_zenodo_lgbm_only.py --week 8

No PyTorch dependency — safe to run after a high-memory graph build.
"""

from __future__ import annotations

import argparse
import gc
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from lightgbm import LGBMClassifier
from sklearn.metrics import (
    average_precision_score,
    balanced_accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

sys.path.insert(0, str(Path(__file__).parent))

from config import PROJECT_ROOT
from zenodo_data import (
    build_features_zenodo,
    build_oulad_compatible_tables,
    filter_window_zenodo,
    iter_log_activity,
    lcpo_split,
    load_zenodo_tables,
    random_student_split,
)

# NOTE: intentionally no torch import — this script must stay PyTorch-free.

_ZENODO_RESULTS_DIR = PROJECT_ROOT / "results" / "zenodo"
_ARTIFACTS_DIR = _ZENODO_RESULTS_DIR / "artifacts"
WEEK = 8


def _select_threshold(proba, labels):
    """Pick threshold that maximises F1 on validation set."""
    from sklearn.metrics import f1_score as _f1
    best_thr, best_f1 = 0.5, -1.0
    for thr in np.linspace(0.1, 0.9, 81):
        pred = (proba >= thr).astype(int)
        score = _f1(labels, pred, zero_division=0)
        if score > best_f1:
            best_f1 = score
            best_thr = thr
    return float(best_thr)


def _metrics(y_true, y_pred, y_proba, threshold):
    return {
        "auroc": float(roc_auc_score(y_true, y_proba)),
        "auprc": float(average_precision_score(y_true, y_proba)),
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "balanced_acc": float(balanced_accuracy_score(y_true, y_pred)),
        "best_threshold": float(threshold),
    }


def run_lgbm(week: int = WEEK, seeds: list = None) -> dict:
    """Run LightGBM random-split + LCPO on pre-built Zenodo artifacts."""
    if seeds is None:
        seeds = [42]

    print("  Loading tables and building VLE features...")
    raw = load_zenodo_tables()
    compat = build_oulad_compatible_tables(raw)
    student_info = compat["student_info"]
    start_dates = raw["start_dates"]

    chunks = []
    for yr, log_df in iter_log_activity():
        year_courses = start_dates[start_dates["year"] == yr]["course_id"].unique()
        for course_id in year_courses:
            base_id = course_id.rstrip(" 12").strip()
            try:
                filtered = filter_window_zenodo(
                    log_df, yr, base_id, week * 7, start_dates
                )
                chunks.append(filtered)
            except ValueError:
                pass
        del log_df
        gc.collect()
    log_w = pd.concat(chunks, ignore_index=True) if chunks else pd.DataFrame()
    del chunks
    gc.collect()

    df_feats = build_features_zenodo(log_w, student_info)
    del log_w
    gc.collect()

    enroll_path = _ARTIFACTS_DIR / f"week{week:02d}_enrollments.parquet"
    enrollments = pd.read_parquet(enroll_path)
    enroll_reset = enrollments.reset_index(drop=True)

    # Deduplicate before merge (build_features_zenodo may return duplicate enrollment keys)
    df_feats_dedup = df_feats.drop_duplicates(
        ["id_student", "code_module", "code_presentation"]
    ).reset_index(drop=True)
    merged = enroll_reset[["id_student", "code_module", "code_presentation"]].merge(
        df_feats_dedup[["id_student", "code_module", "code_presentation",
                        "vle_total", "vle_mean", "vle_std"]],
        on=["id_student", "code_module", "code_presentation"],
        how="left",
    )
    X_full = merged[["vle_total", "vle_mean", "vle_std"]].fillna(0)
    y_full = enrollments["target"].values

    random_rows, lcpo_rows = [], []

    # Random-student split
    print(f"  Random-student split (seeds={seeds})...")
    for seed in seeds:
        tr_s, val_s, te_s = random_student_split(enrollments, seed=seed)
        X_tr, y_tr = X_full[tr_s.values], y_full[tr_s.values]
        X_val, y_val = X_full[val_s.values], y_full[val_s.values]
        X_te, y_te = X_full[te_s.values], y_full[te_s.values]
        clf = LGBMClassifier(n_estimators=100, random_state=seed, verbose=-1)
        clf.fit(X_tr, y_tr)
        val_proba = clf.predict_proba(X_val)[:, 1]
        thr = _select_threshold(val_proba, y_val) if (
            y_val.sum() > 0 and (len(y_val) - y_val.sum()) > 0
        ) else 0.5
        te_proba = clf.predict_proba(X_te)[:, 1]
        te_pred = (te_proba >= thr).astype(int)
        random_rows.append({
            "dataset": "zenodo", "week": week, "model": "LightGBM",
            "split_type": "random_student", "fold_or_seed": seed,
            "feature_set": "vle_only",
            **_metrics(y_te, te_pred, te_proba, thr),
        })
        print(f"    seed={seed}  AUROC={random_rows[-1]['auroc']:.4f}")

    # LCPO
    print("  LCPO folds...")
    presentations = (
        enroll_reset[["code_module", "code_presentation"]]
        .drop_duplicates()
        .sort_values(["code_module", "code_presentation"])
        .itertuples(index=False)
    )
    for fold_idx, row in enumerate(presentations):
        tr_mask, te_mask = lcpo_split(enroll_reset, row.code_module, row.code_presentation)
        ho_mod, ho_pres = row.code_module, row.code_presentation
        X_tr, y_tr = X_full[tr_mask.values], y_full[tr_mask.values]
        X_te, y_te = X_full[te_mask.values], y_full[te_mask.values]
        if y_te.sum() == 0 or (len(y_te) - y_te.sum()) == 0:
            continue
        # 10% of train students → val
        train_stu = enroll_reset.loc[tr_mask.values, "id_student"].unique()
        rng = np.random.default_rng(fold_idx)
        val_size = max(1, int(0.10 * len(train_stu)))
        val_stu = set(rng.choice(train_stu, size=val_size, replace=False))
        val_m = tr_mask.values & enroll_reset["id_student"].isin(val_stu).to_numpy()
        X_val, y_val = X_full[val_m], y_full[val_m]
        clf = LGBMClassifier(n_estimators=100, random_state=42, verbose=-1)
        clf.fit(X_tr, y_tr)
        val_proba = clf.predict_proba(X_val)[:, 1]
        thr = _select_threshold(val_proba, y_val) if (
            y_val.sum() > 0 and (len(y_val) - y_val.sum()) > 0
        ) else 0.5
        te_proba = clf.predict_proba(X_te)[:, 1]
        te_pred = (te_proba >= thr).astype(int)
        lcpo_rows.append({
            "dataset": "zenodo", "week": week, "model": "LightGBM",
            "split_type": "lcpo", "fold_or_seed": fold_idx,
            "held_out_module": ho_mod, "held_out_presentation": ho_pres,
            "feature_set": "vle_only",
            **_metrics(y_te, te_pred, te_proba, thr),
        })
        print(f"    fold {fold_idx:02d} {ho_mod}/{ho_pres}  AUROC={lcpo_rows[-1]['auroc']:.4f}")

    return {"random": random_rows, "lcpo": lcpo_rows}


def main():
    p = argparse.ArgumentParser(description="Zenodo LightGBM VLE-only baseline")
    p.add_argument("--week", type=int, default=WEEK)
    p.add_argument("--seeds", nargs="+", type=int, default=[42, 123, 7, 17, 99])
    args = p.parse_args()

    results = run_lgbm(week=args.week, seeds=args.seeds)
    all_rows = results["random"] + results["lcpo"]
    df = pd.DataFrame(all_rows)

    _ZENODO_RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = _ZENODO_RESULTS_DIR / "comparison_results.csv"
    df.to_csv(out_path, index=False)
    print(f"\nResults → {out_path}")

    rand = df[df["split_type"] == "random_student"]
    lcpo = df[df["split_type"] == "lcpo"]
    print(f"LightGBM random AUROC: {rand['auroc'].mean():.4f} ± {rand['auroc'].std():.4f}")
    if not lcpo.empty:
        print(f"LightGBM LCPO   AUROC: {lcpo['auroc'].mean():.4f} ± {lcpo['auroc'].std():.4f}")


if __name__ == "__main__":
    main()
